name: Github Actions Demo
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '15 6 * * 0'
  workflow_dispatch:

jobs:
    build:
        name: "Build"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4 
            - run: |
                echo ${{ github.event_name }}
                echo ${{ github.ref_name }}
                ls -al