name: Demo Workflow
run-name: Demo Workflow ${{ github.job }}

defaults:
  run:
    shell: pwsh

on: [push]

jobs:
    demo:
        name: "Demo job"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4 
            - run: |
                echo YAY!